### ISSUE TITLE
Chrome Android touch input

### ISSUE THREAD

**Issue by d3nd3** [espruino/EspruinoWebIDE#238] opened 2020-07-13 04:10 UTC
I am unable to click the tool buttons like upload save load and open with my touch screen. I can only click them when i connect a mouse to my tablet. Can it be improved to allow touch input too? Would help me out. Because i do not have BLE on my pc, so i am forced to use my tablet to upload code.

**Comment by gfwilliams** [comment] 2020-07-13 06:41
Can you maybe take a video or something of what's not working? I use this surprisingly often on my phone and it works perfectly with touch.

>  i do not have BLE on my pc, so i am forced to use my tablet to upload code.

You can actually use the 'relay mode' - connect to https://www.espruino.com/ide/relay/ on your phone then copy the code displayed onto settings in your PC - then you can use the normal IDE, sending data via your phone.

**Comment by d3nd3** [comment] 2020-07-13 12:21
Hm, the relay key supplied is empty, any suggestions ?

**Comment by gfwilliams** [comment] 2020-07-13 13:03
Do you have a normal Android version to try out?

I've tried several versions including an Android 10 right now and those buttons all work fine (including the emulator). Actually does it work now after clearing the cache?

If it doesn't, maybe getting some debug logs from Chrome might help?

**Comment by d3nd3** [comment] 2020-07-13 13:56
https://jaketrent.com/post/handling-touch-click-browser/

**Comment by d3nd3** [comment] 2020-07-13 14:49
I cleared the cache, didnt solve it.
I checked if it was an issue with the javascript routine addEventListenerClick , but it wasn't because that fired fine in another tab on a different page.
Sorry if my post about touchstart event annoyed you, but I can continue to try and fix this , if it benefits the project?

**Comment by d3nd3** [comment] 2020-07-13 14:50
Okay some interesting feedback : I believe its something related to drag and drop of the vertical splitter. When i pressed Rotate orientation to horizontal split between code and REPL, the buttons start to work. I'll have to remember that one, for the time being it helps me. I will do more research.

**Comment by d3nd3** [comment] 2020-07-13 15:04
I believe its js/libs/splitster.js interacting with js/libs/jquery-ui-1.10.1.custom.js.  The ui-helper is consuming the click event only when the page is displayed with vertical split because the draggable area overlaps with the buttons in that mode.  Solution should be quite obvious from here on, do you want me to output a complete solution or you can handle the rest? Perhaps try to reproduce what i describe your end.

**Comment by gfwilliams** [comment] 2020-07-13 15:10
Thanks - yes, I'm definitely up for getting this fixed.

I have spent a decent amount of time making the IDE work on Android/iOS devices, so I'm not totally new to touchstart/etc. The IDE actually uses https://github.com/furf/jquery-ui-touch-punch to wrap the touchstart/etc into mouse events - and while hacky it seems to be reasonably well used.

Thanks for looking into this more... If you could contribute a fix that'd be great - sorry for the slow replies but I've been attempting to reproduce before adding anything - however I can't seem to on my devices, regardless of the orientation.

**Comment by gfwilliams** [comment] 2020-07-13 15:15
Oh... Now I can reproduce I think. Can you try on your phone/tablet literally just tapping the button? Try *really hard* not to move your finger.

I think you're right - if your finger moves while on the button, splitster grabs the mouse event and eats it. But if you just tap then (at least for me) it works fine.

Probably how likely your press is to be interpreted as a touch vs a touch + move depends on the device manufacturer.

**Comment by d3nd3** [comment] 2020-07-13 16:29
hey i've found the solution!! Happy.
https://github.com/furf/jquery-ui-touch-punch/issues/233

> This is a longtime known issue apparently (see #109 for a solution). I integrated this and #196 fix into one version, see this repo here if you need.

https://github.com/nobitagit/jquery-ui-touch-punch

He has patched a version of ui-touch-punch for this specific problem. I tested it and it works. Literally 1 step fix, since we're already using this library.

**Comment by d3nd3** [comment] 2020-07-13 16:44
>  however I can't seem to on my devices, regardless of the orientation.
I think it might be specific to certain devices / OS versions... Thats what it said in one of the issues of furf github.   An issue on some devices can still be a nuisance to a large amount of users though.

**Comment by gfwilliams** [comment] 2020-07-14 06:47
Fixed with https://github.com/espruino/EspruinoWebIDE/pull/240 - thanks for tracking this down and doing a PR for the fix!

**Closed by gfwilliams** 2020-07-14 06:47 UTC
